//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_NURSE_RECORDS
    {
        public string ID { get; set; }
        public string NURSE_CODE { get; set; }
        public string PATIENT_ID { get; set; }
        public string VISIT_ID { get; set; }
        public string NURSING_CLASS { get; set; }
        public Nullable<System.DateTime> NURSE_TIME { get; set; }
        public string BODY_TEMPERATURE { get; set; }
        public string HEART_RATE { get; set; }
        public string BREATHE { get; set; }
        public string BLOOD_PRESSURE { get; set; }
        public string SP_ZERO_TWO { get; set; }
        public string REMARKS { get; set; }
        public string SIGNATURE { get; set; }
        public Nullable<short> PROCESSING_STATUS { get; set; }
        public string OPERATE_TYPE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<int> BODY_TEMPERATURE_NO { get; set; }
        public Nullable<int> HEART_RATE_NO { get; set; }
        public Nullable<int> BREATHE_NO { get; set; }
        public Nullable<int> BLOOD_PRESSURE_NO { get; set; }
        public Nullable<int> SP_ZERO_TWO_NO { get; set; }
        public Nullable<int> REMARKS_NO { get; set; }
        public Nullable<int> SIGNATURE_NO { get; set; }
        public Nullable<int> PROCESSING_STATUS_NO { get; set; }
    }
}
