//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNIS_T_REPORT_DATA
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string STATUS { get; set; }
        public string ERROR_MSG { get; set; }
        public string UPDATE_FLAG { get; set; }
        public string XML_URL { get; set; }
        public string PDF_URL { get; set; }
        public string PATIENT_ID { get; set; }
        public string VISIT_ID { get; set; }
        public string PATIENT_NAME { get; set; }
        public string REPORT_NO { get; set; }
        public string REPORT_TYPE { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public Nullable<System.DateTime> VALID_DATE { get; set; }
        public string PAGE_ORENTION { get; set; }
        public string PAGE_SIZE { get; set; }
        public string PAGE_COUNT { get; set; }
        public string PUBLISH_SYSTEM { get; set; }
        public string CREATE_DEPT { get; set; }
        public string TYPE { get; set; }
    }
}
