//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOC_ANTENATAL_CARE_RECORD> DOC_ANTENATAL_CARE_RECORD { get; set; }
        public DbSet<DOC_DAYOUR_ENTRYEXIT_RECORD> DOC_DAYOUR_ENTRYEXIT_RECORD { get; set; }
        public DbSet<DOC_MICROGLYCEMIC_RECORD> DOC_MICROGLYCEMIC_RECORD { get; set; }
        public DbSet<DOC_NURSING_RECORD> DOC_NURSING_RECORD { get; set; }
        public DbSet<DOC_POSTPARTUM_NURSING_RECORD> DOC_POSTPARTUM_NURSING_RECORD { get; set; }
        public DbSet<DOC_RECORDS> DOC_RECORDS { get; set; }
    }
}
